#!/usr/bin/env python3
"""Generate machine-readable indexes from frontmatter/IDs across the brain.

Currently generates:
  - 03-work/INDEX.md   from each work unit's `overview.md` YAML frontmatter
                        (type, stage, tier, owner, updated)
  - 06-decisions/INDEX.md   from `## DEC-XXX — <title>` headers + Status field
  - 05-requirements/INDEX.md   from `REQ-FUN-XXX` / `REQ-NFR-XXX` / `BR-XXX`
                        table rows

Indexes are deterministic: regenerating from unchanged source content
produces byte-identical output. `make validate` regenerates them in memory
and fails if the committed file differs (staleness check) — see
`scripts/validate_structure.py`.

Usage:
    python3 scripts/build_indexes.py [--check]

    --check   don't write files; exit 1 if any index would change (used by
              `make validate`)
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
GENERATED_NOTE = (
    "<!-- GENERATED by scripts/build_indexes.py — do not edit by hand. -->\n"
)

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)
FIELD_RE = re.compile(r"^(\w[\w-]*):\s*(.*?)\s*(?:#.*)?$")


def parse_frontmatter(text: str) -> dict[str, str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    fields: dict[str, str] = {}
    for line in m.group(1).splitlines():
        fm = FIELD_RE.match(line)
        if fm:
            fields[fm.group(1)] = fm.group(2)
    return fields


def build_work_index() -> str | None:
    work_dir = ROOT / "03-work"
    if not work_dir.is_dir():
        return None
    rows = []
    for unit_dir in sorted(work_dir.iterdir()):
        if not unit_dir.is_dir() or unit_dir.name.startswith("_"):
            continue
        overview = unit_dir / "overview.md"
        if not overview.is_file():
            continue
        fields = parse_frontmatter(overview.read_text(encoding="utf-8"))
        rows.append((
            unit_dir.name,
            fields.get("type", "_PENDING_"),
            fields.get("stage", "_PENDING_"),
            fields.get("tier", "_PENDING_"),
            fields.get("owner", "_PENDING_"),
            fields.get("updated", "_PENDING_"),
        ))
    lines = [GENERATED_NOTE, "\n# Work units index\n\n",
             "| Work unit | Type | Stage | Tier | Owner | Updated |\n",
             "|---|---|---|---|---|---|\n"]
    for name, type_, stage, tier, owner, updated in rows:
        lines.append(f"| [{name}]({name}/overview.md) | {type_} | {stage} | "
                      f"{tier} | {owner} | {updated} |\n")
    if not rows:
        lines.append("| _none yet_ | | | | | |\n")
    return "".join(lines)


def build_decisions_index() -> str | None:
    log = ROOT / "06-decisions/decision-log.md"
    if not log.is_file():
        return None
    text = log.read_text(encoding="utf-8")
    blocks = re.split(r"^## (?=DEC-\d+(?!\w))", text, flags=re.M)[1:]
    rows = []
    for b in blocks:
        header = b.splitlines()[0].strip()
        ident_m = re.match(r"(DEC-\d+(?!\w))\s*[-—]\s*(.*)", header)
        if not ident_m:
            print(f"WARNING: build_indexes: could not parse decision header "
                  f"{header!r} in 06-decisions/decision-log.md — omitted from INDEX.md",
                  file=sys.stderr)
            continue
        ident, title = ident_m.group(1), ident_m.group(2)
        status_m = re.search(r"\*\*Status\*\*\s*\|\s*([^|]+)\|", b)
        status = status_m.group(1).strip() if status_m else "_PENDING_"
        rows.append((ident, title, status))
    lines = [GENERATED_NOTE, "\n# Decisions index\n\n",
             "| ID | Title | Status |\n", "|---|---|---|\n"]
    for ident, title, status in rows:
        lines.append(f"| [{ident}](decision-log.md#{ident.lower()}) | {title} | {status} |\n")
    if not rows:
        lines.append("| _none yet_ | | |\n")
    return "".join(lines)


def build_requirements_index() -> str | None:
    req_dir = ROOT / "05-requirements"
    if not req_dir.is_dir():
        return None
    row_re = re.compile(r"^\|\s*((?:REQ-FUN|REQ-NFR|BR)-\d+)\s*\|\s*([^|]*)\|\s*([^|]*)\|", re.M)
    rows = []
    for md in sorted(req_dir.glob("*.md")):
        if md.name == "INDEX.md":
            continue
        for m in row_re.finditer(md.read_text(encoding="utf-8")):
            rows.append((m.group(1), md.name, m.group(2).strip(), m.group(3).strip()))
    lines = [GENERATED_NOTE, "\n# Requirements index\n\n",
             "| ID | File | Title | Status |\n", "|---|---|---|---|\n"]
    for ident, fname, title, status in rows:
        lines.append(f"| {ident} | {fname} | {title or '_PENDING_'} | {status or '_PENDING_'} |\n")
    if not rows:
        lines.append("| _none yet_ | | | |\n")
    return "".join(lines)


INDEXES = {
    "03-work/INDEX.md": build_work_index,
    "06-decisions/INDEX.md": build_decisions_index,
    "05-requirements/INDEX.md": build_requirements_index,
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                     help="don't write; exit 1 if any index is stale")
    args = ap.parse_args()

    stale: list[str] = []
    for rel, builder in INDEXES.items():
        content = builder()
        if content is None:
            continue
        path = ROOT / rel
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        stale.append(rel)
        if not args.check:
            path.write_text(content, encoding="utf-8")

    if args.check:
        if stale:
            print("Stale indexes (run `make index`):")
            for rel in stale:
                print(f"  {rel}")
            return 1
        print("Indexes up to date.")
        return 0

    if stale:
        print("Regenerated:")
        for rel in stale:
            print(f"  {rel}")
    else:
        print("Indexes already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
