#!/usr/bin/env python3
"""Sync external skills from the engineering harness and regenerate native
tool projections so Claude Code, Codex, and Antigravity discover every skill.

Config (brain.config.json):
    "harness": {
        "source": "../ml-python-base",
        "external_skills": ["brainstorming", "writing-plans", ...]
    }

What it does:
  1. Pulls each listed skill from the harness source — accepts both shapes:
     flat `.github/skills/<name>.md` or dir `.github/skills-external/<name>/`
     — into this repo's `.github/skills-external/<name>/SKILL.md`, recording
     a sha256 per skill in `skills-lock.json`.
  2. Regenerates `.claude/skills/`, `.codex/skills/`, `.agents/skills/` from
     internal skills (`.github/skills/*.md`) + synced external dirs. Each
     projection carries a `.generated-manifest.tsv`; do not edit by hand.
  3. Ensures `.agents/rules/brain-rules.md` points Antigravity at AGENTS.md.

Idempotent. Run after every harness release adoption.
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CFG = ROOT / "brain.config.json"
EXTERNAL = ROOT / ".github" / "skills-external"
INTERNAL = ROOT / ".github" / "skills"
LOCK = ROOT / "skills-lock.json"
PROJECTIONS = [ROOT / ".claude" / "skills",
               ROOT / ".codex" / "skills",
               ROOT / ".agents" / "skills"]


def sha256(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    for p in sorted(path.rglob("*") if path.is_dir() else [path]):
        if p.is_file():
            h.update(p.read_bytes())
    return h.hexdigest()


def find_in_harness(harness: pathlib.Path, name: str) -> pathlib.Path | None:
    for cand in (harness / ".github" / "skills-external" / name,
                 harness / ".github" / "skills" / f"{name}.md",
                 harness / ".claude" / "skills" / name):
        if cand.exists():
            return cand
    return None


def install_external(src: pathlib.Path, name: str) -> pathlib.Path:
    dest = EXTERNAL / name
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    if src.is_dir():
        for item in src.iterdir():
            if item.name.startswith("."):
                continue
            (shutil.copytree if item.is_dir() else shutil.copy2)(item, dest / item.name)
        if not (dest / "SKILL.md").exists():
            mds = list(dest.glob("*.md"))
            if mds:
                mds[0].rename(dest / "SKILL.md")
    else:
        shutil.copy2(src, dest / "SKILL.md")
    return dest


def internal_skills():
    if not INTERNAL.is_dir():
        return []
    return [p for p in sorted(INTERNAL.glob("*.md")) if p.name != "README.md"]


def regenerate_projections():
    entries = []  # (name, kind, source_path)
    for f in internal_skills():
        entries.append((f.stem, "internal", f))
    if EXTERNAL.is_dir():
        for d in sorted(EXTERNAL.iterdir()):
            if d.is_dir() and (d / "SKILL.md").exists():
                entries.append((d.name, "external", d))
    for proj in PROJECTIONS:
        if proj.exists():
            shutil.rmtree(proj)
        proj.mkdir(parents=True)
        rows = []
        for name, kind, src in entries:
            dest = proj / name
            if src.is_dir():
                shutil.copytree(src, dest)
            else:
                dest.mkdir()
                shutil.copy2(src, dest / "SKILL.md")
            rows.append(f"{name}\t{kind}\t{src.relative_to(ROOT)}")
        (proj / ".generated-manifest.tsv").write_text(
            "# generated by scripts/sync_skills.py — do not edit\n" + "\n".join(rows) + "\n",
            encoding="utf-8")
    return entries


def ensure_antigravity_rules():
    rules = ROOT / ".agents" / "rules"
    rules.mkdir(parents=True, exist_ok=True)
    f = rules / "brain-rules.md"
    if not f.exists():
        f.write_text(
            "# Workspace rules — Company Brain\n\n"
            "All operating rules for this repository live in `AGENTS.md` at the\n"
            "repo root — read it first and follow it. Skills are projected into\n"
            "`.agents/skills/` (generated; do not edit — run `make sync-skills`).\n",
            encoding="utf-8")


def main() -> int:
    cfg = json.loads(CFG.read_text(encoding="utf-8")) if CFG.is_file() else {}
    harness_cfg = cfg.get("harness", {})
    source = harness_cfg.get("source", "../ml-python-base")
    wanted = harness_cfg.get("external_skills", [])
    harness = (ROOT / source).resolve()

    lock = {"source": source, "skills": {}}
    missing = []
    if wanted and not harness.is_dir():
        print(f"WARNING: harness source not found at {harness} — skipping external sync,")
        print("         regenerating projections from what is already present.")
        wanted = []
    for name in wanted:
        src = find_in_harness(harness, name)
        if src is None:
            missing.append(name)
            continue
        dest = install_external(src, name)
        lock["skills"][name] = {"origin": str(src.relative_to(harness)),
                                "sha256": sha256(dest)}
        print(f"[sync] {name}  <-  {src.relative_to(harness)}")
    if wanted:
        LOCK.write_text(json.dumps(lock, indent=2) + "\n", encoding="utf-8")

    entries = regenerate_projections()
    ensure_antigravity_rules()
    print(f"[proj] {len(entries)} skills projected to .claude/ .codex/ .agents/")
    if missing:
        print(f"WARNING: not found in harness: {', '.join(missing)}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
